In [2]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor

In [3]:
df = '/content/drive/MyDrive/kc_house_data.csv'
df = pd.read_csv(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [4]:
df.head()

           id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [6]:
X = df.drop(columns= ['id','price','date','lat','long'])

In [7]:
X.shape

(21613, 16)

In [8]:
y = df['price']
y.shape

(21613,)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 3)

In [10]:
clf = RandomForestRegressor(n_estimators= 100, bootstrap= True, oob_score= True)

In [11]:
clf

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=True,
                      random_state=None, verbose=0, warm_start=False)

In [12]:
clf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=True,
                      random_state=None, verbose=0, warm_start=False)

In [13]:
score_random_forest_train = clf.score(X_train,y_train)
score_random_forest_train

0.9729703056560999

In [14]:
score_random_forest_test = clf.score(X_test, y_test)
score_random_forest_test

0.8162075435167503

In [15]:
clf.oob_score_

0.8039798665669432

In [16]:
clf.feature_importances_

array([0.00535401, 0.01528301, 0.26187224, 0.0231852 , 0.00427379,
       0.02029272, 0.02016113, 0.00539348, 0.36588451, 0.02068453,
       0.01090308, 0.08817595, 0.00341561, 0.07918086, 0.04903168,
       0.02690819])

In [18]:
clf_features = pd.DataFrame({'feature': X_train.columns,'feature_importance': clf.feature_importances_})
clf_features.sort_values(by = 'feature_importance', ascending= False)

          feature  feature_importance
8           grade            0.365885
2     sqft_living            0.261872
11       yr_built            0.088176
13        zipcode            0.079181
14  sqft_living15            0.049032
15     sqft_lot15            0.026908
3        sqft_lot            0.023185
9      sqft_above            0.020685
5      waterfront            0.020293
6            view            0.020161
1       bathrooms            0.015283
10  sqft_basement            0.010903
7       condition            0.005393
0        bedrooms            0.005354
4          floors            0.004274
12   yr_renovated            0.003416

Bagging model

In [ ]:
bagg_tree = BaggingRegressor()
bagg_tree.fit(X_train, y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=False,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [ ]:
bagg_tree_train_score = bagg_tree.score(X_train, y_train)
bagg_tree_train_score

0.9611530359797467

In [ ]:
bagg_tree_test_score = bagg_tree.score(X_test, y_test)
bagg_tree_test_score

0.8012592087137114

In [ ]:
price_prediction = pd.DataFrame({'actual price': y_test,'price_predition': bagg_tree.predict(X_test)})
price_prediction

       actual price  price_predition
4131       525000.0     4.384167e+05
17459     1870000.0     1.581589e+06
2192       750000.0     6.981000e+05
12418      244900.0     1.645000e+05
15773      275000.0     3.795510e+05
...             ...              ...
13430      450000.0     4.582950e+05
4805       224975.0     1.899074e+05
13631      255000.0     2.408100e+05
7637       339900.0     3.044000e+05
10002      465000.0     4.303000e+05

[5404 rows x 2 columns]

1. Grade and sqft_living are the most important features for your model.
2. n_estimators